-- View: vw_product_performance
-- Purpose: Summarize sales performance, units sold, gross revenue, and order metrics per product
-- Business Metric: Evaluates product category profitability, product popularity, and sales velocity
-- Updated: Evaluated dynamically on query execution (always reflects latest completed orders)
-- Used By: Product Operations, Merchandising Team, Sales Dashboard
--
-- Business Question Answered:
--   Which products and categories are driving top revenue and highest sales volume, 
--   filtering only for completed, non-cancelled customer transactions?
-- 
-- Columns:
--   product_id: Unique product identifier
--   product_name: Display name of the product
--   category: Category classification (e.g., Electronics, Software, Hardware)
--   product_line: High-level product line grouping
--   unit_price: Current listed unit price of product
--   total_orders: Count of distinct completed orders containing this product
--   total_units_sold: Total quantity of units sold across completed orders
--   total_revenue: Gross revenue generated by product (quantity * unit_price)
--   avg_units_per_order: Average units sold per order for this product

CREATE VIEW IF NOT EXISTS vw_product_performance AS
SELECT 
    p.product_id,
    p.product_name,
    p.category,
    p.product_line,
    p.unit_price,
    COUNT(DISTINCT oi.order_id) AS total_orders,
    COALESCE(SUM(oi.quantity), 0) AS total_units_sold,
    COALESCE(SUM(oi.quantity * oi.unit_price), 0.0) AS total_revenue,
    ROUND(AVG(oi.quantity), 2) AS avg_units_per_order
FROM products p
JOIN order_items oi ON p.product_id = oi.product_id
JOIN orders o ON oi.order_id = o.order_id
WHERE o.order_status = 'completed'
GROUP BY p.product_id, p.product_name, p.category, p.product_line, p.unit_price;
